// PROJECTS
export const FORM_PROJECT = 'NEW FORM PROJECT';
export const GET_PROJECTS = 'GET PROJECTS';
export const ADD_PROJECTS = 'ADD PROJECTS';
export const VALIDATE_PROJECT_FORM = 'VALIDATE PROJECT FORM';
export const CURRENT_PROJECT = 'CURRENT PROJECT';
export const DELETE_PROJECT = 'DELETE PROJECT';
export const DELETE_PROJECT_ERROR = 'DELETE PROJECT ERROR';

// TASKS
export const GET_TASKS_PROJECT = 'GET TASKS PROJECT';
export const ADD_TASK = 'ADD TASK';
export const VALIDATE_TASK_FORM = 'VALIDATE TASK FORM';
export const DELETE_TASK = 'DELETE TASK';
export const SELECT_CURRENT_TASK = 'SELECT CURRENT TASK';
export const EDIT_TASK = 'EDIT TASK';
export const CLEAN_TASK = 'CLEAN TASK';

// ALERTS
export const SHOW_ALERT = 'SHOW ALERT';
export const HIDE_ALERT = 'HIDE ALERT';

// AUTH
export const SIGNUP_SUCCESS = 'SIGNUP SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP FAILURE';
export const LOGIN_SUCCESS = 'LOGIN SUCCESS';
export const LOGIN_FAILURE = 'LOGIN FAILURE';
export const GET_USER = 'GET USER';
export const LOGOUT = 'LOGOUT';
