export const FORM_PROJECT = 'NEW FORM PROJECT';
export const GET_PROJECTS = 'GET PROJECTS';
export const ADD_PROJECTS = 'ADD PROJECTS';
export const VALIDATE_PROJECT_FORM = 'VALIDATE PROJECT FORM';
export const CURRENT_PROJECT = 'CURRENT PROJECT';